### PR TITLE
removed subscription and added is_hacker to User

### PR DESCRIPTION
**Pull request by Coding-Cactus**
Replit removed the subscription field for some reason, which causes an error any time you want to do pretty much anything. So I removed the subscription field and replaced it with is_hacker.

### CODE REVIEW

**Comment by Coding-Cactus** [comment]
:/ it does work

**Comment by Coding-Cactus** [comment]
got there in the end 😂

**Comment by rayhanadev** [comment]
Oop I don't really want to reopen this but @Coding-Cactus do you know of any other important changes to the API? I want to be sure my package is up to date as well.

**Comment by Coding-Cactus** [comment]
Nope, just noticed this using my ruby wrapper earlier so fixed it on here too. Not particularly sure why they removed the subscription field.

**Comment by mat-1** [comment]
I released this as v1.0.0 so people know it's a breaking change, btw

**Comment by rayhanadev** [comment]
@Coding-Cactus Ah, okay gotcha. 
@mat-1 woah awesome.

**Pull request merged**
