### PR TITLE
Plz add my talk bot

### PR DESCRIPTION
**Pull request by RaidTheWeb**
It is really good plz add

### CODE REVIEW

**Comment by PotentialStyx** [comment]
BRUHHHHH you copied @IreTheKID's bot not cool

**Comment by RaidTheWeb** [comment]
?
No I wrote a framework and IreTheKID uses it

**Comment by PotentialStyx** [comment]
Really lol I thought Ire made it first sorry

**Comment by RaidTheWeb** [comment]
Np

**Comment by mat-1** [comment]
already added

**Pull request closed without merging**
