### PR TITLE
Fix report post too

### PR DESCRIPTION
**Pull request by PotentialStyx**
#12 fixed comments but apparently it's the same thing for posts, just quickly fixing it

@mat-1 sry for bothering you but can you merge this as well

### CODE REVIEW

**Comment by mat-1** [comment]
Is this actually necessary? Reports only return `LazyPost`s and `LazyComment`s. `Post`s already include all the information.

**Comment by PotentialStyx** [comment]
Idk why but for coding cactus at least it is for some reason getting Comments + Posts not LazyComment's and LazyPost's

**Comment by mat-1** [comment]
What's his code?

**Comment by PotentialStyx** [comment]
I'll ask him later when I can

**Comment by Coding-Cactus** [comment]
Hi @mat-1 maybe I'm just doing this wrong, but here is the code
image


also, if it is a comment that was reported (where get_attached() doesn't error), get_attached() just returns the report itself.
image

**Comment by mat-1** [comment]
This isn't really a bug, just that get_attached wasn't implemented in a way that made sense. Resolved by #14

**Pull request closed without merging**
